[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "turnip"
version = "0.1.0"
description = "LLM orchestration utilities"
readme = "README.md"
requires-python = ">=3.10"
authors = [{name = "Turnip Team"}]
